# Generated by Django 6.0.2 on 2026-02-28 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='testresult',
            name='test_name',
            field=models.CharField(default='General Technical Screen', max_length=100),
        ),
    ]
